name: Release (Production version for A2 GH Pages)
on: [workflow_dispatch]

jobs:
  validate-tag:
    name: Validate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag to Build on
        run: |
          TAG="${{ github.ref_name }}"
          if [[ ! "$TAG" =~ ^v ]]; then
            echo "The workflow was run from an invalid ref."
            echo "Expected the ref name to start with a \"v\"."
            echo "If using the GitHub UI, please select a tag from the \"Use workflow from\" dropdown."
            exit 1
          fi

  run-tests:
    name: Run Tests
    needs: validate-tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.21.0
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Test
        run: npm run test

  build-pages:
    name: Build GitHub Page
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.21.0
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: GIT_REF=${{ github.ref_name }} npm run build -- --base=/abicus/

      - name: Upload Pages artefact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  build-docker:
    needs: run-tests
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build
        id: docker-build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          build-args: GIT_REF=${{ github.ref_name }}

      - name: Assume AWS role
        uses: digabi/workflows-common/actions/assume-digabi-aws-role@main
        with:
          aws-account-id: ${{ secrets.UTILITY_AWS_ACCOUNT_ID }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Tag Docker Image
        run: docker tag ${{ steps.docker-build.outputs.imageid }} ${{ steps.login-ecr.outputs.registry }}/abicus-prod:${{ github.ref_name }}

      - name: Push Docker Image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/abicus-prod:${{ github.ref_name }}
